from pathlib import Path
import csv
import json
import yaml
import shutil
from zipfile import ZipFile

EXPORT_DIR = Path(__file__).resolve().parents[2] / "storage" / "exports"
EXPORT_DIR.mkdir(parents=True, exist_ok=True)


def _confidence_score(confidence: str) -> int:
    value = (confidence or "medium").lower().strip()
    return {"low": 33, "medium": 66, "high": 100}.get(value, 66)


def _confidence_color(confidence: str) -> str:
    value = (confidence or "medium").lower().strip()
    return {"low": "#ffe766", "medium": "#ffb84d", "high": "#ff6666"}.get(value, "#ffb84d")


def build_attack_navigator_layer(report, mappings):
    """Build a MITRE ATT&CK Navigator layer JSON file.

    This file can be uploaded directly into ATT&CK Navigator via:
    Open Existing Layer -> Upload from local.
    """
    techniques = {}
    for mapping in mappings:
        technique_id = (mapping.technique_id or "").strip()
        if not technique_id:
            continue

        existing = techniques.get(technique_id)
        score = _confidence_score(mapping.confidence)
        comment = f"{mapping.technique_name}: {mapping.evidence or 'Mapped from report intelligence.'}"

        if not existing or score > existing["score"]:
            techniques[technique_id] = {
                "techniqueID": technique_id,
                "score": score,
                "color": _confidence_color(mapping.confidence),
                "comment": comment[:1000],
                "enabled": True,
                "metadata": [
                    {"name": "Technique Name", "value": mapping.technique_name or "Unknown"},
                    {"name": "Confidence", "value": mapping.confidence or "medium"},
                    {"name": "Source Report", "value": report.filename},
                ],
            }

    return {
        "name": f"RuleForge - {report.title or report.filename}",
        "versions": {
            "attack": "16",
            "navigator": "5.1.0",
            "layer": "4.5",
        },
        "domain": "enterprise-attack",
        "description": f"ATT&CK Navigator layer generated from {report.filename} by ThreatIntel RuleForge. Scores: low=33, medium=66, high=100.",
        "filters": {"platforms": ["Windows", "Linux", "macOS", "Network", "PRE", "Containers", "Office 365", "SaaS", "IaaS", "Azure AD", "Google Workspace"]},
        "sorting": 0,
        "layout": {"layout": "side", "aggregateFunction": "average", "showID": False, "showName": True},
        "hideDisabled": False,
        "techniques": list(techniques.values()),
        "gradient": {
            "colors": ["#ffe766", "#ffb84d", "#ff6666"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "Low confidence", "color": "#ffe766"},
            {"label": "Medium confidence", "color": "#ffb84d"},
            {"label": "High confidence", "color": "#ff6666"},
        ],
        "metadata": [
            {"name": "Generated By", "value": "ThreatIntel RuleForge"},
            {"name": "Source File", "value": report.filename},
        ],
        "showTacticRowBackground": False,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }


def export_report(report, iocs, mappings, detections) -> str:
    base = EXPORT_DIR / f"report_{report.id}_export"
    if base.exists():
        shutil.rmtree(base)
    base.mkdir(parents=True, exist_ok=True)

    csv_path = base / "iocs.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["type", "value", "confidence", "approved", "enrichment_source", "enrichment_summary", "context"])
        for ioc in iocs:
            writer.writerow([ioc.ioc_type, ioc.value, ioc.confidence, ioc.is_approved, ioc.enrichment_source, ioc.enrichment_summary, ioc.source_context])

    mitre_export = [
        {
            "technique_id": m.technique_id,
            "technique_name": m.technique_name,
            "evidence": m.evidence,
            "confidence": m.confidence,
        } for m in mappings
    ]

    mitre_path = base / "mitre_mapping.yaml"
    with mitre_path.open("w", encoding="utf-8") as f:
        yaml.safe_dump(mitre_export, f, sort_keys=False)

    mitre_json_path = base / "mitre_mapping.json"
    mitre_json_path.write_text(json.dumps(mitre_export, indent=2), encoding="utf-8")

    navigator_path = base / "attack_navigator_layer.json"
    navigator_path.write_text(json.dumps(build_attack_navigator_layer(report, mappings), indent=2), encoding="utf-8")

    rules_dir = base / "sigma_rules"
    rules_dir.mkdir(exist_ok=True)
    for rule in detections:
        safe_name = "".join(c if c.isalnum() else "_" for c in rule.title.lower())[:80]
        (rules_dir / f"{safe_name}.yml").write_text(rule.rule_content, encoding="utf-8")

    def render_summary(summary_text):
        if not summary_text:
            return "No summary generated."
        try:
            overview = json.loads(summary_text)
            lines = [overview.get("executive_summary", "")]
            lines.append(f"\n**Threat Actor:** {overview.get('threat_actor', 'Unknown')}")
            lines.append(f"\n**Targeting:** {overview.get('targeting', 'Not identified')}")
            if overview.get("malware_families"):
                lines.append("\n**Malware / Tools:** " + ", ".join(overview.get("malware_families", [])))
            for heading, key in [("Attack Chain", "attack_chain"), ("Key Findings", "key_findings"), ("Detection Opportunities", "detection_opportunities"), ("Analyst Notes", "analyst_notes")]:
                items = overview.get(key, []) or []
                if items:
                    lines.append(f"\n## {heading}\n" + "\n".join([f"- {item}" for item in items]))
            return "\n".join(lines)
        except Exception:
            return summary_text

    md_path = base / "summary.md"
    md_path.write_text(f"""# Threat Intelligence Extraction Report

## Source

- File: {report.filename}
- Status: {report.processing_status}

## Summary

{render_summary(report.summary)}

## IOC Count

{len(iocs)} indicators extracted.

## MITRE Techniques

""" + "\n".join([f"- {m.technique_id}: {m.technique_name} ({m.confidence})" for m in mappings]) + "\n\n## ATT&CK Navigator\n\n- Upload `attack_navigator_layer.json` to MITRE ATT&CK Navigator.\n- `mitre_mapping.yaml` and `mitre_mapping.json` contain the same mapping evidence in machine-readable formats.\n\n## Detection Rules\n\n" + "\n".join([f"- {d.title} [{d.severity}]" for d in detections]), encoding="utf-8")

    zip_path = EXPORT_DIR / f"report_{report.id}_export.zip"
    with ZipFile(zip_path, "w") as zipf:
        for file in base.rglob("*"):
            if file.is_file():
                zipf.write(file, file.relative_to(base))
    return str(zip_path)
